CREATE DATABASE IF NOT EXISTS libraryproject;

USE libraryproject;

CREATE TABLE IF NOT EXISTS book_description (
	BookDescID INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(140) NOT NULL,
	Genre VARCHAR(25),
    Summary VARCHAR (300),
    ISBN VARCHAR(15) NOT NULL,
    PRIMARY KEY (BookDescID) 
);

CREATE TABLE IF NOT EXISTS book (
	BookID INT NOT NULL AUTO_INCREMENT,
	BookDescID INT NOT NULL,
	PRIMARY KEY (BookID),
	FOREIGN KEY (BookDescID) REFERENCES book_description (BookDescID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS borrower (
	BorrowerID INT NOT NULL AUTO_INCREMENT,
    BorrowerFirstName VARCHAR(25) NOT NULL,
    BorrowerLastName VARCHAR(25) NOT NULL,
    PRIMARY KEY (BorrowerID)
);

CREATE TABLE IF NOT EXISTS borrowed_book (
	BorrowedBookID INT NOT NULL AUTO_INCREMENT,
    BookID INT NOT NULL,
    BorrowerID INT NOT NULL,
    CheckOutDate DATE NOT NULL,
    DueDate DATE NOT NULL,
    ReturnedDate DATE,
    PRIMARY KEY (BorrowedBookID),
    FOREIGN KEY (BookID) REFERENCES book(BookID) ON DELETE CASCADE,
    FOREIGN KEY (BorrowerID) REFERENCES borrower(BorrowerID) ON DELETE CASCADE
);